### ISSUE TITLE
Add non-exchange services to the wiki

### ISSUE THREAD

**Issue by xaur** [jzbz/decred#1]
There are some services that don't let you trade Decred directly but still contribute to Decred ecosystem. Payment processors like CoinPayments, GloBee and CoinGate. For example, the latter allows merchants to accept DCR and even has a small [dedicated page](https://coingate.com/accept/dcr/decred). They also cared to [introduce](https://www.reddit.com/r/decred/comments/72adth/you_can_pay_with_decred_at_stores_that_use/) themselves on our reddit.

**Comment by jzbz** [comment]
Yes, this has been don now on the official exchanges page at https://decred.org/exchanges/
